apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc
  name: grpc
spec:
  ports:
  - name: "30002"
    port: 5005
    targetPort: 5005
    nodePort: 30002
  selector:
    service: grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc
  name: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc
  template:
    metadata:
      labels:
        service: grpc
    spec:
      containers:
      - image: hainche/grpc:latest
        name: grpc
        imagePullPolicy: Always        
